### ISSUE TITLE
【QA】how can i run these demo on mac

### ISSUE THREAD

**Issue by dandingol03** [emeiri/ogldev#10]

**Comment by emeiri** [comment]
According to Apple (https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html) OpenGL is not longer supported on the Mac since MacOS 10.14. There's a list of machines that still support it: https://support.apple.com/en-us/HT202823. You will need to setup a project in XCode or any other C++ environment and possible build GLEW and FreeGLUT yourself unless binaries for Mac are available.

**Comment by emeiri** [comment]
I hope to be able to support the Mac in the future (probably when I get to Vulkan...). For now I will close this issue.
