### ISSUE TITLE
Getting build errors on Windows

### ISSUE THREAD

**Issue by rajendrasp** [emeiri/ogldev#27]
I opened ogldev_vs_2022.sln and trying to build the solution. But it is giving me few errors.

2>C:\D\Learning\OpenGL\ogldev\Include\ogldev_vulkan.h(28,10): fatal  error C1083: Cannot open include file: 'vulkan/vulkan.h': No such file or directory

1>C:\D\Learning\OpenGL\ogldev\Common\ogldev_skydome.cpp(232,19): error C2039: 'SetRotate': is not a member of 'SkydomeTechnique'

1>C:\D\Learning\OpenGL\ogldev\Terrain12\terrain.h(28,10): fatal  error C1083: Cannot open include file: 'terrain_technique.h': No such file or directory

1>c1xx : fatal  error C1083: Cannot open source file: '..\..\..\Terrain12\terrain_demo12.cpp': No such file or directory

1>c1xx : fatal  error C1083: Cannot open source file: '..\..\..\Terrain12\terrain_technique.cpp': No such file or directory

Am I missing something on my setup?

Thanks

**Comment by emeiri** [comment]
Thanks for the bug report. I fixed a few problems so some of the errors should go away. The Vulkan error is probably because of a mismatch of SDK include dir. Right now the two Vulkan projects have 'C:\VulkanSDK\1.3.246.0\Include' in their include path. You may need to fix this for your installation. 'Terrain12' is actually a work in progress. I will checkin all the missing sources when the next video is out. Also expect only the 'Debug' config to build because due to lack of time that's the only config that I'm actually maintaining.

**Comment by emeiri** [comment]
IIRC these issues have been fixed. Please reopen if needed.
